version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - shop_static_volume:/shop/static/
    networks:
      - shop_main
    restart: always

volumes:
  shop_static_volume:
      
networks:
  shop_main: